export const courtData = [
  {
    name: 'S1C1',
    description: 'S1 Football Court',
    sportType: 'Football',
    area: 'S1',
  },
  {
    name: 'S1C2',
    description: 'S1 Basketball Court',
    sportType: 'Basketball',
    area: 'S1',
  },
  {
    name: 'S1C3',
    description: 'S1 Volleyball Court',
    sportType: 'Volleyball',
    area: 'S1',
  },
  {
    name: 'S1C4',
    description: 'S1 Badminton Court',
    sportType: 'Badminton',
    area: 'S1',
  },
  {
    name: 'S1C5',
    description: 'S1 Tennis Court',
    sportType: 'Tennis',
    area: 'S1',
  },
  {
    name: 'S2C1',
    description: 'S2 Football Court',
    sportType: 'Football',
    area: 'S2',
  },
  {
    name: 'S2C2',
    description: 'S2 Basketball Court',
    sportType: 'Basketball',
    area: 'S2',
  },
  {
    name: 'S2C3',
    description: 'S2 Volleyball Court',
    sportType: 'Volleyball',
    area: 'S2',
  },
  {
    name: 'S2C4',
    description: 'S2 Badminton Court',
    sportType: 'Badminton',
    area: 'S2',
  },
  {
    name: 'S2C5',
    description: 'S2 Tennis Court',
    sportType: 'Tennis',
    area: 'S2',
  },
  {
    name: 'S3C1',
    description: 'S3 Football Court',
    sportType: 'Football',
    area: 'S3',
  },
  {
    name: 'S3C2',
    description: 'S3 Basketball Court',
    sportType: 'Basketball',
    area: 'S3',
  },
  {
    name: 'S3C3',
    description: 'S3 Volleyball Court',
    sportType: 'Volleyball',
    area: 'S3',
  },
  {
    name: 'S3C4',
    description: 'S3 Badminton Court',
    sportType: 'Badminton',
    area: 'S3',
  },
  {
    name: 'S3C5',
    description: 'S3 Tennis Court',
    sportType: 'Tennis',
    area: 'S3',
  },
  {
    name: 'S4C1',
    description: 'S4 Football Court',
    sportType: 'Football',
    area: 'S4',
  },
  {
    name: 'S4C2',
    description: 'S4 Basketball Court',
    sportType: 'Basketball',
    area: 'S4',
  },
  {
    name: 'S4C3',
    description: 'S4 Volleyball Court',
    sportType: 'Volleyball',
    area: 'S4',
  },
  {
    name: 'S4C4',
    description: 'S4 Badminton Court',
    sportType: 'Badminton',
    area: 'S4',
  },
  {
    name: 'S4C5',
    description: 'S4 Tennis Court',
    sportType: 'Tennis',
    area: 'S4',
  },
  {
    name: 'S5C1',
    description: 'S5 Football Court',
    sportType: 'Football',
    area: 'S5',
  },
  {
    name: 'S5C2',
    description: 'S5 Basketball Court',
    sportType: 'Basketball',
    area: 'S5',
  },
  {
    name: 'S5C3',
    description: 'S5 Volleyball Court',
    sportType: 'Volleyball',
    area: 'S5',
  },
  {
    name: 'S5C4',
    description: 'S5 Badminton Court',
    sportType: 'Badminton',
    area: 'S5',
  },
  {
    name: 'S5C5',
    description: 'S5 Tennis Court',
    sportType: 'Tennis',
    area: 'S5',
  },
  {
    name: 'S6C1',
    description: 'S6 Football Court',
    sportType: 'Football',
    area: 'S6',
  },
  {
    name: 'S6C2',
    description: 'S6 Basketball Court',
    sportType: 'Basketball',
    area: 'S6',
  },
  {
    name: 'S6C3',
    description: 'S6 Volleyball Court',
    sportType: 'Volleyball',
    area: 'S6',
  },
  {
    name: 'S6C4',
    description: 'S6 Badminton Court',
    sportType: 'Badminton',
    area: 'S6',
  },
  {
    name: 'S6C5',
    description: 'S6 Tennis Court',
    sportType: 'Tennis',
    area: 'S6',
  },
  {
    name: 'S7C1',
    description: 'S7 Football Court',
    sportType: 'Football',
    area: 'S7',
  },
  {
    name: 'S7C2',
    description: 'S7 Basketball Court',
    sportType: 'Basketball',
    area: 'S7',
  },
  {
    name: 'S7C3',
    description: 'S7 Volleyball Court',
    sportType: 'Volleyball',
    area: 'S7',
  },
  {
    name: 'S7C4',
    description: 'S7 Badminton Court',
    sportType: 'Badminton',
    area: 'S7',
  },
  {
    name: 'S7C5',
    description: 'S7 Tennis Court',
    sportType: 'Tennis',
    area: 'S7',
  },
  {
    name: 'S8C1',
    description: 'S8 Football Court',
    sportType: 'Football',
    area: 'S8',
  },
  {
    name: 'S8C2',
    description: 'S8 Basketball Court',
    sportType: 'Basketball',
    area: 'S8',
  },
  {
    name: 'S8C3',
    description: 'S8 Volleyball Court',
    sportType: 'Volleyball',
    area: 'S8',
  },
  {
    name: 'S8C4',
    description: 'S8 Badminton Court',
    sportType: 'Badminton',
    area: 'S8',
  },
  {
    name: 'S8C5',
    description: 'S8 Tennis Court',
    sportType: 'Tennis',
    area: 'S8',
  },
  {
    name: 'S9C1',
    description: 'S9 Football Court',
    sportType: 'Football',
    area: 'S9',
  },
  {
    name: 'S9C2',
    description: 'S9 Basketball Court',
    sportType: 'Basketball',
    area: 'S9',
  },
  {
    name: 'S9C3',
    description: 'S9 Volleyball Court',
    sportType: 'Volleyball',
    area: 'S9',
  },
  {
    name: 'S9C4',
    description: 'S9 Badminton Court',
    sportType: 'Badminton',
    area: 'S9',
  },
  {
    name: 'S9C5',
    description: 'S9 Tennis Court',
    sportType: 'Tennis',
    area: 'S9',
  },
  {
    name: 'S10C1',
    description: 'S10 Football Court',
    sportType: 'Football',
    area: 'S10',
  },
  {
    name: 'S10C2',
    description: 'S10 Basketball Court',
    sportType: 'Basketball',
    area: 'S10',
  },
  {
    name: 'S10C3',
    description: 'S10 Volleyball Court',
    sportType: 'Volleyball',
    area: 'S10',
  },
  {
    name: 'S10C4',
    description: 'S10 Badminton Court',
    sportType: 'Badminton',
    area: 'S10',
  },
  {
    name: 'S10C5',
    description: 'S10 Tennis Court',
    sportType: 'Tennis',
    area: 'S10',
  },
];
